Encom/Models/Certificate.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Encom.Models
{
    public class Certificate : BaseEntity
    {
        [NotMapped]
        public IFormFile? Photo { get; set; }
        public string? ImagePath { get; set; }
    }
}

Encom/Areas/EncomAdmin/Controllers/CertificatesController.cs
using Encom.DAL;
using Encom.Helpers;
using Encom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Encom.Areas.EncomAdmin.Controllers
{
    [Area("EncomAdmin")]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class CertificatesController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        private readonly UserManager<User> _userManager;

        public CertificatesController(AppDbContext db
            , IWebHostEnvironment env
            , UserManager<User> userManager)
        {
            _db = db;
            _env = env;
            _userManager = userManager;
        }

        #region Index
        public IActionResult Index(int pageIndex = 1)
        {
            IQueryable<Certificate> query = _db.Certificates.Where(x => !x.IsDeleted);
            return View(PageNatedList<Certificate>.Create(query, pageIndex, 10, 10));
        }
        #endregion

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Certificate model)
        {
            if (model.Photo != null)
            {
                string currentUsername = _userManager.GetUserName(HttpContext.User);
                if (!(model.Photo.CheckFileContenttype("image/jpeg") || model.Photo.CheckFileContenttype("image/png")))
                {
                    ModelState.AddModelError("Photo", $"{model.Photo.FileName} is not the correct format");
                }

                if (model.Photo.CheckFileLength(5120))
                {
                    ModelState.AddModelError("Photo", $"Photo must be less than 5 mb");
                }

                model.ImagePath = await model.Photo.CreateFileAsync(_env, "src", "assets", "images"); // UNDONE: Source deyise biler
                model.CreatedAt = DateTime.UtcNow.AddHours(4);
                model.CreatedBy = currentUsername;
            }
            else
            {
                ModelState.AddModelError("Photo", "Image is empty");
            }

            var validationErrors = new Dictionary<string, string[]>();
            if (!ModelState.IsValid)
            {
                validationErrors = ModelState.ToDictionary(
                    err => err.Key,
                    err => err.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );

                return Json(new { success = false, errors = validationErrors });
            }

            await _db.AddAsync(model);
            await _db.SaveChangesAsync();
            return Json(new { success = true });
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();

            Certificate? dbCertificate = await _db.Certificates.FirstOrDefaultAsync(x => x.Id == id && !x.IsDeleted);

            if (dbCertificate == null) return NotFound();

            return View(dbCertificate);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Certificate certificate)
        {
            if (id == null) return BadRequest();

            Certificate? dbCertificate = await _db.Certificates.FirstOrDefaultAsync(x => x.Id == id && !x.IsDeleted);
            if (dbCertificate == null) return NotFound();

            #region Image
            if (certificate.Photo != null)
            {
                if (!(certificate.Photo.CheckFileContenttype("image/jpeg") || certificate.Photo.CheckFileContenttype("image/png")))
                {
                    ModelState.AddModelError("Photo", $"{certificate.Photo.FileName} is not the correct format");
                }

                if (certificate.Photo.CheckFileLength(5120))
                {
                    ModelState.AddModelError("Photo", $"Photo must be less than 5 mb");
                }

                string previousFilePath = dbCertificate.ImagePath;
                if (previousFilePath != null)
                {
                    FileHelper.DeleteFile(previousFilePath, _env, "src", "assets", "images");
                }

                dbCertificate.ImagePath = await certificate.Photo.CreateFileAsync(_env, "src", "assets", "images");
            }
            #endregion
            string currentUsername = _userManager.GetUserName(HttpContext.User);

            dbCertificate.UpdatedBy = currentUsername;
            dbCertificate.UpdatedAt = DateTime.UtcNow.AddHours(4);

            var validationErrors = new Dictionary<string, string[]>();
            if (!ModelState.IsValid)
            {
                validationErrors = ModelState.ToDictionary(
                    err => err.Key,
                    err => err.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );

                return Json(new { success = false, errors = validationErrors });
            }

            await _db.SaveChangesAsync();
            return Json(new { success = true } );
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            Certificate? certificate = await _db.Certificates
                .FirstOrDefaultAsync(b => b.Id == id && b.IsDeleted == false);

            if (certificate == null) return NotFound();

            if (certificate.ImagePath != null)
            {
                FileHelper.DeleteFile(certificate.ImagePath, _env, "src", "assets", "images");
            }

            _db.Certificates.Remove(certificate);
            await _db.SaveChangesAsync();
            return Json(new { success = true });

        }
        #endregion
    }
}

Encom/Areas/EncomAdmin/Views/Certificates/Create.cshtml
@model Certificate

<div class="row mt-3">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">@language.Getkey("CreateCertificate")</div>
                <hr>
                <form method="post" enctype="multipart/form-data" id="createCertificateForm">
                    <div class="form-group">
                        <label asp-for="@Model.Photo">@language.Getkey("Image")</label>
                        <input accept="image/*" asp-for="@Model.Photo" class="form-control">
                        <span asp-validation-for="@Model.Photo" class="text-danger" style="display:block"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary px-5">@language.Getkey("Submit")</button>
                        <a asp-action="Index" class="btn btn-secondary">@language.Getkey("Cancel")</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            $('#createCertificateForm').submit(function (e) {
                e.preventDefault();

                var $form = $(this);
                var $submitButton = $form.find('button[type="submit"]');
                $submitButton.prop('disabled', true);

                var formData = new FormData(this);

                $.ajax({
                    url: '@Url.Action("Create", "Certificates")',
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.success) {
                            window.location.href = '@Url.Action("Index", "Certificates")';
                        } else {
                            $('.text-danger').text('');

                            $.each(response.errors, function (key, value) {
                                $('[data-valmsg-for="' + key + '"]').text(value);
                            });
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    },
                    complete: function () {
                        $submitButton.prop('disabled', false);
                    }
                });
            });
        });
    </script>
}

Encom/Areas/EncomAdmin/Views/Certificates/Index.cshtml
@using Encom.Helpers
@model PageNatedList<Certificate>
@{
    ViewData["Title"] = "Index";
    int count = (Model.PageIndex - 1) * 3;
    int No = (Model.PageIndex - 1) * 10;
}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h2 class="card-title">@language.Getkey("Certificates")</h2>
                    <a asp-area="EncomAdmin" asp-controller="Certificates" asp-action="Create" class="btn btn-primary text-white mr-2">@language.Getkey("Create")</a>

                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    №
                                </th>
                                <th>
                                    @language.Getkey("Image")
                                </th>
                                <th>
                                    @language.Getkey("Actions")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Certificate item in Model)
                            {
                                No++;
                                <tr>
                                    <td>
                                        @No
                                    </td>
                                    <td>
                                        <img style="height:75px; width:135px; border-radius:0px; object-fit:contain" src="~/src/assets/images/@item.ImagePath">
                                    </td>
                                    <td style="vertical-align: middle; text-align: center; ">
                                        <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-info text-white mr-2">@language.Getkey("Update")</a>
                                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger text-white mr-2 deleteIndex">@language.Getkey("Delete")</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.HasPrev)
                {
                    <li class="page-item">
                        <a class="page-link" asp-area="EncomAdmin" asp-controller="Certificates" asp-action="Index"
                           asp-route-pageIndex="@(Model.PageIndex - 1)">@language.Getkey("Previous")</a>
                    </li>
                }
                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    <li class="page-item @(i == Model.PageIndex ? "active" : "")"><a class="page-link" asp-area="EncomAdmin" asp-controller="Certificates" asp-action="Index" asp-route-pageIndex="@i">@i</a></li>
                }
                @if (Model.HasNext)
                {
                    <li class="page-item">
                        <a class="page-link" asp-area="EncomAdmin" asp-controller="Certificates" asp-action="Index"
                           asp-route-pageIndex="@(Model.PageIndex + 1)">@language.Getkey("Next")</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

@section Scripts {
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <style>
        .swal-title {
            color: black;
        }

        .swal-text {
            color: #555;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on('click', '.deleteIndex', function (e) {
                e.preventDefault();
                var deleteUrl = $(this).attr('href');
                var row = $(this).closest('tr');

                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            $.ajax({
                                url: deleteUrl,
                                type: 'DELETE',
                                success: function (response) {
                                    if (response.success) {
                                        swal({
                                            icon: "success",
                                            text: "Your data has been deleted!",
                                            buttons: false,
                                            timer:1000
                                        });
                                        row.fadeOut(1000, function () {
                                            $(this).remove();
                                        });
                                    } else {
                                        swal({
                                            icon: "error",
                                            text: response.message,
                                            buttons: false,
                                            timer: 1000
                                        });
                                    }
                                },
                                error: function (error) {
                                    console.error('Error:', error);
                                    swal({
                                        icon: "error",
                                        text: "An error occurred. Please try again later.",
                                        buttons: false,
                                        timer: 2000
                                    });
                                }
                            });
                        } else {
                            swal({
                                icon: "error",
                                text: "Delete operation cancelled!",
                                buttons: false,
                                timer: 1000
                            });
                        }
                    });
            });
        });
    </script>
}

Encom/Areas/EncomAdmin/Views/Certificates/Update.cshtml
@model Certificate

<div class="row mt-3">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">@language.Getkey("UpdateCertificate")</div>
                <hr>
                <div style="margin:5px">
                    <img style="width:150px; height:100px;object-fit:contain;" src="~/src/assets/images/@Model.ImagePath">
                </div>
                <form method="post" enctype="multipart/form-data" id="updateCertificateForm">
                    <div class="form-group">
                        <label asp-for="@Model.Photo">@language.Getkey("Image")</label>
                        <input accept="image/*" asp-for="@Model.Photo" class="form-control">
                        <span asp-validation-for="@Model.Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary px-5">@language.Getkey("Submit")</button>
                        <a asp-action="Index" class="btn btn-secondary">@language.Getkey("Cancel")</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            $('#updateCertificateForm').submit(function (e) {
                e.preventDefault();

                var $form = $(this);
                var $submitButton = $form.find('button[type="submit"]');
                $submitButton.prop('disabled', true);

                var formData = new FormData(this);

                $.ajax({
                    url: '@Url.Action("Update", "Certificates")',
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.success) {
                            window.location.href = '@Url.Action("Index", "Certificates")';
                        } else {
                            $('.text-danger').text('');

                            $.each(response.errors, function (key, value) {
                                $('[data-valmsg-for="' + key + '"]').text(value);
                            });
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    },
                    complete: function () {
                        $submitButton.prop('disabled', false);
                    }
                });
            });
        });
    </script>
}